import { TrustPage } from "@/components/trust-page";
import { createMetadata } from "@/lib/metadata";
import { site } from "@/data/site";
export const metadata = createMetadata(
  "Privacy Policy for NOUN Compass",
  "Read how NOUN Compass handles visitor information, analytics, contact messages, and requests to access, correct, or delete data.",
  "/privacy-policy",
);
export default function Page() { return <TrustPage title="Privacy Policy" eyebrow="Your privacy" intro="This policy explains what information NOUN Compass may collect and how it is used."><h2>Information we collect</h2><p>Public visitors may provide a name, email address, and message through the contact form. Visitors may also provide an email address with explicit consent to join the NounCompass updates list. Account holders may store a display name, programme, level, semester, entry mode, study centre, exam mode, selected course codes, available study days, learning progress, notification preferences, support messages, and membership status.</p><h2>Email updates</h2><p>Newsletter addresses are stored with the consent source and date and may be synchronized to a dedicated Brevo contact list. Joining is optional, does not create a paid membership, and may be withdrawn through the unsubscribe link in a future campaign or by contacting NounCompass.</p><h2>Information we do not request</h2><p>Do not give NounCompass your NOUN password, OTP, payment-card details, identity documents, or private portal access. Flutterwave handles checkout details; NounCompass stores the transaction reference, provider transaction identifier, amount, currency, status, and timestamps needed to grant and support access.</p><h2>Cookies and analytics</h2><p>Authentication uses secure session cookies. Google Analytics records general usage events such as signup, course selection, practice completion, and checkout state without sending question text, answers, NOUN credentials, or academic records.</p><h2>How information is used</h2><p>Information supports personalised planning, progress, access control, payment reconciliation, opted-in updates, reminders, support, abuse prevention, and site improvement. We do not sell personal information.</p><h2>Service providers</h2><p>Supabase provides account and database infrastructure, Flutterwave processes membership payments, Brevo stores opted-in contacts and delivers operational or consented email, Vercel hosts the application, and Google Analytics measures usage. Each provider processes relevant data under its own terms and privacy commitments.</p><h2>Retention and rights</h2><p>You may request access, correction, export, unsubscribe, or account deletion through support or by emailing <a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a>. Account deletion removes or anonymises profile, learning, notification, and support data while limited transaction records may be retained for payment, fraud, accounting, or legal obligations.</p><h2>Changes</h2><p>We may update this policy as the platform and legal requirements evolve. Material changes will be reflected on this page before newly affected processing begins.</p></TrustPage>; }
