import Link from "next/link";
import { CheckoutButton } from "@/components/checkout-button";
import { Breadcrumbs } from "@/components/article-elements";
import { isCheckoutAvailable, platformConfig } from "@/lib/platform/config";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("NOUN Compass Semester Pass", "See what is free and what the optional 180-day NounCompass exam-preparation pass includes.", "/membership");

export default function MembershipPage() {
  return <main id="main-content"><div className="category-hero"><div className="container"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Membership" }]} /><span className="eyebrow">Optional exam-preparation access</span><h1>One semester. One clear price.</h1><p>Core student guidance, official resource links, calculators, and basic planning stay free. The pass pays for original reviewed preparation and progress tools.</p></div></div><section className="container section membership-layout"><article className="membership-card"><span className="eyebrow">Semester pass</span><div className="membership-price"><strong>₦2,500</strong><span>one payment</span></div><p>180 days of premium access. This is not an automatic subscription.</p><ul><li>Full published question banks</li><li>Untimed practice and timed mocks</li><li>Detailed explanations</li><li>Weak-topic and revision tracking</li><li>Progress exports and reminders</li></ul><CheckoutButton available={isCheckoutAvailable()} /><small>Paystack transaction charges apply to NounCompass, not as a hidden second membership price.</small></article><div className="membership-comparison"><section><h2>Always free</h2><ul><li>Original public guides</li><li>Official course-material links</li><li>Fee, CGPA, result, and study tools</li><li>Basic semester dashboard</li><li>Published timetable matching</li></ul></section><section><h2>Premium when banks pass review</h2><ul><li>More than the free diagnostic allowance</li><li>Complete explanations and performance history</li><li>Five-box revision scheduling</li><li>Timed mock sessions</li><li>Cross-device preparation progress</li></ul></section><aside className="trust-note"><strong>No academic shortcuts</strong><p>The pass does not buy active TMA answers, leaked examinations, guaranteed grades, or access to NOUN systems.</p><Link href="/terms">Read the membership terms</Link></aside></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Offer", name: "NOUN Compass Semester Pass", price: platformConfig.semesterPass.amountKobo / 100, priceCurrency: "NGN", description: "180 days of optional premium exam-preparation access", url: "https://nouncompass.me/membership" }) }} /></main>;
}
