import { TrustPage } from "@/components/trust-page";
import { createMetadata } from "@/lib/metadata";
import { site } from "@/data/site";
export const metadata = createMetadata(
  "Terms of Use for NOUN Compass",
  "Review the terms that govern how you use NOUN Compass, our educational content, external links, and site availability.",
  "/terms",
);
export default function Page() { return <TrustPage title="Terms of Use" eyebrow="Using this website" intro="These terms explain how to use NOUN Compass reasonably and what to expect from the site."><h2>Educational information</h2><p>NOUN Compass provides independent educational guides, tools, original practice, and study help. Your own NOUN record and current official pages remain the final authority for registration, fees, deadlines, examinations, and academic decisions.</p><h2>Accounts</h2><p>Provide accurate account information, protect your password, and do not share access in a way that bypasses membership controls. NounCompass may suspend access used for fraud, scraping, credential abuse, disruption, or prohibited assessment services.</p><h2>Semester Pass</h2><p>The optional Semester Pass is one payment for 180 days of access to premium content that has passed editorial review. It is not an automatic subscription. Free public guides, official resource links, and core planning tools do not require purchase.</p><h2>Academic integrity</h2><p>Do not use NounCompass to obtain or distribute leaked examinations, active TMA answers, impersonation services, altered records, or other academic misconduct. Practice content is for learning and does not guarantee any result.</p><h2>Accuracy and availability</h2><p>We work to keep content and platform services useful, but schedules, fees, requirements, and source pages can change. We do not guarantee uninterrupted access or that unofficial planning output will match every account-specific record.</p><h2>External links and payments</h2><p>External NOUN pages remain outside our control. Paystack processes membership checkout; NounCompass does not receive NOUN fees or process university payments.</p><h2>Refunds and contact</h2><p>Payment concerns follow the <a href="/refund-policy">Refund Policy</a>. Other questions can be sent to <a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a>.</p></TrustPage>; }
