import Link from "next/link";
import { Breadcrumbs, DisclaimerBox } from "@/components/article-elements";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("NOUN Student Tools", "Practical NOUN tools for checking results, estimating CGPA, reviewing fees, planning study time, and starting free exam practice.", "/tools");

export default function ToolsPage() {
  return <main id="main-content"><div className="category-hero"><div className="container"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Tools" }]} /><span className="eyebrow">Plan with clarity</span><h1>Student tools</h1><p>Useful tools for checking records, planning fees, estimating CGPA, organizing study time, and testing your exam readiness.</p></div></div><div className="container narrow section"><section id="result-checker" className="tool-panel"><span className="tool-number">01</span><h2>NOUN result checker</h2><p>Enter your matriculation number to open your result statement on the official NOUN result portal.</p><Link className="button" href="/tools/result-checker">Check your result</Link></section><section id="fee-guide" className="tool-panel"><span className="tool-number">02</span><h2>School fees checker</h2><p>Review the available semester breakdown by faculty, programme, level, and semester. Use the result to plan, then confirm the final amount on your portal before you pay.</p><Link className="button" href="/fees">Check your school fees</Link></section><section id="study-planner" className="tool-panel"><span className="tool-number">03</span><h2>NOUN study planner</h2><p>Build a weekly study timetable around your courses, free hours, workdays, and study rhythm. Course suggestions come from the data already listed on NounCompass.</p><Link className="button" href="/tools/study-planner">Open the study planner</Link></section><section id="cgpa-calculator" className="tool-panel"><span className="tool-number">04</span><h2>NOUN CGPA calculator</h2><p>Enter your course units and final scores to estimate grade points, quality points, semester GPA, and your running CGPA.</p><Link className="button" href="/tools/cgpa-calculator">Open the CGPA calculator</Link></section><section id="exam-diagnostic" className="tool-panel"><span className="tool-number">05</span><h2>Free exam diagnostic</h2><p>Sign in with a free account to try sample questions and see where you need more work. Full practice, timed mocks, and revision tools remain part of the Semester Pass.</p><Link className="button" href="/dashboard/practice">Start free diagnostic</Link><p><Link href="/exam-prep">See supported course coverage first</Link></p></section><DisclaimerBox /></div></main>;
}
