import Link from "next/link";
import { Breadcrumbs, DisclaimerBox } from "@/components/article-elements";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("NOUN Student Tools", "Simple planning tools for NOUN fees, CGPA, deadlines, and study scheduling.", "/tools");

export default function ToolsPage() {
  return <main id="main-content"><div className="category-hero"><div className="container"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Tools" }]} /><span className="eyebrow">Plan with clarity</span><h1>Student tools</h1><p>We only publish tools that are ready for real student use.</p></div></div><div className="container narrow section"><section id="fee-guide" className="tool-panel"><span className="tool-number">01</span><h2>School fees checker</h2><p>Review the available semester breakdown by faculty, programme, level, and semester. Use the result to plan, then confirm the final amount on your portal before you pay.</p><Link className="button" href="/fees">Check your school fees</Link></section><section id="study-planner" className="tool-panel"><span className="tool-number">02</span><h2>NOUN study planner</h2><p>Build a weekly study timetable around your courses, free hours, workdays, and study rhythm. Course suggestions come from the data already indexed on NounCompass.</p><Link className="button" href="/tools/study-planner">Open the study planner</Link></section><section id="cgpa-calculator" className="tool-panel"><span className="tool-number">03</span><h2>NOUN CGPA calculator</h2><p>Enter your course units and final scores to estimate grade points, quality points, semester GPA, and your running CGPA.</p><Link className="button" href="/tools/cgpa-calculator">Open the CGPA calculator</Link></section><DisclaimerBox /></div></main>;
}
